### PR TITLE
Rename PREFIX build variable

### PR DESCRIPTION
**Pull request by toonst**
This simplifies integration with other software projects. PREFIX defines the directory where build files end up. In other projects eg. RIOT, PREFIX is used for different purposes, eg. arm-none-eabi.

I'm not sure if it's a good idea to push this through, hence the PR.
This probably breaks some tests, @ISY-Thomas can you check if this is managable?
Also in places where picoTCP is integrated using its own build system this might need some changes.
Remarks?

### CODE REVIEW

**Comment by toonst** [comment]
Also, documentation will have to be changed:
https://github.com/tass-belgium/picotcp/wiki/Porting-the-build-to-another-compiler---IDE
https://github.com/tass-belgium/picotcp/wiki/Build-process-explained
https://github.com/tass-belgium/picotcp/wiki/writing-unit-tests

**Comment by frederikvs** [comment]
If we want to go through with this, we need to seriously consider the implications.. If we do it, this needs to be made very clear in the release notes as well.
(maybe you should start compiling a TODO list somewhere)

But isn't there an easier way to do this? At the integration with RIOT do something like `make -C picotcp PREFIX=build/picotcp CROSS_COMPILE=$PREFIX` or similar? (not sure what the integration with RIOT looks like)

**Comment by toonst** [comment]
@frederikvs Yes, it's quiet easy to work around, that's why I'm not sure we should go through with this. If we change it future integrations wont need to work around.

**Comment by danielinux** [comment]
I don't like the idea. `$PREFIX` is in general used to specify destination paths. For the toolchain prefix triplet, riot should be using `$CROSS_COMPILE` instead.

**Comment by danielinux** [comment]
also, as @frederikvs pointed out, if the integration is done via external picoTCP module, make -C is the way to go, and you still may have two separate sets of compile-time variables.

This is how we do in insane-adding-machines/frosted : 
https://github.com/insane-adding-machines/frosted/blob/master/rules/picotcp.mk#L53

**Comment by toonst** [comment]
OK, I was a bit quick with generalizing the way RIOT does things. Let's keep it the way it is. Thanks for the remarks!

**Pull request closed without merging**
