### PR TITLE
Allow headers to be included in any order.

### PR DESCRIPTION
**Pull request by ProgVal**
Hi,

This PR makes headers include all their dependencies, so they do not rely on the dependencies to be included before they are.

I also removed `pico_module_eth.h`, which is used in any other  file and does not seem to be documented; and which fails to compile (`struct eth` is not defined anywhere).

### CODE REVIEW

**Comment by frederikvs** [comment]
Cool, thanks. Mind if I ask how you found all this? Just manually go over things, or do you have a script or something? If there's something automatic, I think we should add it to our jenkins :-)

Also, before I can merge this, would you mind signing our CLA?
https://docs.google.com/forms/d/e/1FAIpQLScitcDtYzpqSSYY5Rwtir3aBEtcPrBn9GK1BovuwXSNIqsutg/viewform

**Comment by ProgVal** [comment]
I used to run rust-bindgen on every header; for detecting these error, it's just like running clang on them.
(It had some issues, so now I [write a `.h` which includes all other headers](https://github.com/ProgVal/picotcp-sys/blob/26270cd/build.rs#L34-L56) and [run rust-bindgen on this one](https://github.com/ProgVal/picotcp-sys/blob/26270cd/build.rs#L22-L32); but some of the fixes in this PR are still useful.)

**Comment by frederikvs** [comment]
@ProgVal could you sign our CLA? Only after that can we merge in your PRs.
https://docs.google.com/forms/d/e/1FAIpQLScitcDtYzpqSSYY5Rwtir3aBEtcPrBn9GK1BovuwXSNIqsutg/viewform
(it's a two-step process : fill in the form, and then modify a wiki page to prove ownership of the github account)

**Comment by ProgVal** [comment]
I filled the form last week, did you check?

**Comment by frederikvs** [comment]
hmm, then our form must have broken, we should have received mail of that. Did you receive a mail with further instructions?

**Comment by frederikvs** [comment]
Hi @ProgVal , I'm sorry to say it took us about a month to figure out who owned the google form and get everything fixed.

Could you please fill in the form again? You should receive an email with instructions to update a wiki page (proves the owner of the github account meant to sign the form). After you've done that, we can merge these PRs :-)

https://docs.google.com/forms/d/e/1FAIpQLScitcDtYzpqSSYY5Rwtir3aBEtcPrBn9GK1BovuwXSNIqsutg/viewform

**Comment by ProgVal** [comment]
Done.

And I just rebased this PR to fix the merge conflicts.

**Comment by frederikvs** [comment]
Good work, thanks. I merged them into development, they'll make it to master at our next release.

Please accept my sincere apologies that it took so long to merge these PRs.

**Pull request merged**
