### PR TITLE
Added linkerflag for unit testing on Ubuntu 16.4

### PR DESCRIPTION
**Pull request by BrechtDeVlieger**
Ubuntu 16.4 requires -lsubunit flag to link the unit test suite module. The linker flags of unit testing are combined into a variable.

### CODE REVIEW

**Comment by frederikvs** [comment]
nice work, but could you modify the PR to merge into development instead of master? (or close this PR and make a new one.)
I forgot to mention this, but all PRs should go to development, and then when we release it goes to master.

**Comment by frederikvs** [comment]
@BrechtDeVlieger sorry to bother you again, but right now the merge has conflicts. Could you take another look, and give me a PR that applies cleanly to the development branch? Thanks.

**Comment by BrechtDeVlieger** [comment]
It should now be able to merge.

**Comment by frederikvs** [comment]
great, thanks

**Pull request merged**
