### PR TITLE
Clarify: socket calls require port to be passed in network byte order

### PR DESCRIPTION
**Pull request by djsavvy**
I just got bitten by this, and am not the only one. (see https://github.com/tass-belgium/picotcp/issues/330) 

@mateusviste argued well in the linked issue why this should be highlighted more explicitly in the manual. 

Please let me know if I need to make any changes to be able to merge this pull request. I have already signed the CLA and am waiting for the confirmation email.

### CODE REVIEW

**Comment by maximevince** [comment]
ping anyone at Altran? @jelledevleeschouwer @frederikvs 
It's sad to see so little interaction and PRs getting merged...

**Comment by jmagnette** [comment]
Hey Maxime,
How are you doing?

I think nobody from Altran is working on picotcp anymore.
A lot happened, a lot of people are gone for some time and just after I
left, I remember people saying that Altran was not going to support picotcp
anymore...

I hope others will answer you back, but I didn't want you to be answer less
😉

See ya one day,
Jérémie

Le jeu. 15 août 2019 à 11:48, Maxime Vincent <notifications@github.com> a
écrit :

**Comment by frederikvs** [comment]
@maximevince I'm no longer at Altran, so unfortunately I can't help...

**Comment by danielinux** [comment]
We do still maintain a (GPL only) fork here: https://gitlab.com/insane-adding-machines/picoTCP - since Altran abandoned the project. Some newer features are only available in our fork.

Merge requests are welcome there.

**Pull request merged**
