### PR TITLE
Bug in fragmentation implementation fixed

### PR DESCRIPTION
**Pull request by jvzp**
@frederikvs, here is the fix for the fragmentation bug! Can you check it out?
Thanks!

### CODE REVIEW

**Comment by phalox** [comment]
@jvzp could you include how you tested the fail + how you verified it no longer fails? Your commit messages can be a bit longer than this :-)

I'm using this:
[first line, short description]

[long description if necesary]
Ticket: [related issue tracking item]
Tested: [instructions on how this was verified, maybe also how to reproduce]

**Comment by jvzp** [comment]
@phalox a few ifdef's were missing concerninng ipv4 fragmentation. I added them and tested the implementation using all of the tests for the CI Lamp.

**Comment by phalox** [comment]
I was looking for a different answer :-) I guess you also tested it with 
picotcpDir $ make -D[SOMETHING] ?

I'd like to know the exact instruction so we can add a test to jenkins for this.

**Comment by jvzp** [comment]
I did not test it yet with that but I will be doing so this afternoon.

**Comment by jvzp** [comment]
@phalox I did just make, since ipv4 fragmentation is compiled within picotcp standardly and it all compiles without errors/warnings

**Comment by phalox** [comment]
And which one failed then before your fix??

**Comment by jvzp** [comment]
none of picotcp... my code from the tass connected device failed by using it.

**Comment by phalox** [comment]
OK, can you then configure a command that will make picotcp compilation fail? :-) We just want picoTCP sanity checks...

I guess something like make -DIPV4_FRAGMENTATION=0 or something?

**Comment by jvzp** [comment]
If I build picoTCP with in the makefile ipv4frag=0 then the code compiles as well..

**Comment by phalox** [comment]
I'm thinking we're not understanding each other :-)

Let's broaden the scope: If we now put the rule in place that no bug fix can be submitted without a test to verify that it's fixed; what should we do then?

**Comment by phalox** [comment]
Looks good, merging back

**Pull request merged**
