### PR TITLE
fix Makefile for OSX

### PR DESCRIPTION
**Pull request by mhagmajer**
This is a follow-up to pull request https://github.com/tass-belgium/picotcp/pull/462 with fix for issue #461.

### CODE REVIEW

**Comment by mhagmajer** [comment]
CC @frederikvs

**Comment by frederikvs** [comment]
Currently there appears to be something wrong with our CI setup. I'm postponing this merge and #464 until we get that sorted out - I don't want you to get a bunch of false positive mails from Jenkins.

**Comment by mhagmajer** [comment]
@frederikvs could you kindly look into the CI setup to see whether these issues were already resolved?

**Comment by frederikvs** [comment]
The first problem on the CI setup has been fixed, now there's another problem with an expired license for one of our tools...

But if you don't mind getting some spam from our Jenkins server I could just merge it in now :-)

**Comment by mhagmajer** [comment]
Frederik, please go ahead. I'm fine with SPAM from Jenkins. I was more worried about this PR being forgotten ;)

**Pull request merged**
